# SPDX-FileCopyrightText: 2023 UnionTech Software Technology Co., Ltd.
#
# SPDX-License-Identifier: LGPL-3.0-or-later

version: 1
defaultRepo: stable
repos:
  stable: https://mirror-repo-linglong.deepin.com
